# Generated by Django 4.1.5 on 2023-01-10 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='started', max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 1, 10, 11, 55, 31, 84903, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
